application:
  developerMode: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bookmarkmanagement
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified'
    username: 'postgres'
    password: 'admin'
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  security:
#    oauth2:
#      client:
#        registration:
#          azure:
#            client-id: 'CLIENT ID'
#            client-secret: 'CLIENT SECRET'
#  servlet:
#    multipart:
#      enabled: true
#      location: ${java.io.tmpdir}
#azure:
#  activedirectory:
#    allow-telemetry: false
#    tenant-id: 'TENANT ID'
#    active-directory-groups: 'ITS-CS-Student-CXt, Dept_ITSCustomerServi'
#    user-group:
#      allowed-groups: 'ITS-CS-Student-CXt, Dept_ITSCustomerServi'
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  playground:
    mapping: /playground
    endpoint: /graphql
    pageTitle: Playground
    headers:
      headerFor: AllTabs
    cdn:
      enabled: false
      version: latest
    settings:
      editor:
        cursorShape: line
        fontFamily: "'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace"
        fontSize: 14
        reuseHeaders: true
        theme: dark
      prettier:
        printWidth: 80
        tabWidth: 2
        useTabs: false
      schema:
        polling:
          enable: true
          endpointFilter: "*localhost*"
          interval: 2000
        disableComments: true
      tracing:
        hideTracingResponse: true
      request:
        credentials: include
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL